### ISSUE TITLE
Please delete @vite/client

### ISSUE THREAD

**Issue by t0byman** [brandcom/cakephp-vite#11]
It seems the newest version of Vite loads the client automatically, can you confirm?
If confirmed, please delete:
```
        $this->Html->script(
            $config->read('development.url', ConfigDefaults::DEVELOPMENT_URL)
            . '/@vite/client',
            [
                'type' => 'module',
                'block' => $options['cssBlock'],
            ]
        );
```
in `ViteScriptsHelper.php`

**Comment by bor-attila** [comment]
What is the problem with autoloading ?

**Comment by bor-attila** [comment]
the documentation in Vite 5.x still reflects to viteclient

https://vitejs.dev/guide/backend-integration.html#backend-integration
