### ISSUE TITLE
CakePHP 5.0 support

### ISSUE THREAD

**Issue by Borderliner** [brandcom/cakephp-vite#14]
Can't seem to add this plugin to a Cake 5 app, showing incompatibility between `5.0` and `5.x-dev` versions. Any help?

**Comment by passchn** [comment]
Does it work now? I don't have a working cake5-install/branch myself currently, so I did not test it. 

See the last commits: 
https://github.com/brandcom/cakephp-vite/commits/cake5

**Comment by passchn** [comment]
Changed the version here: 
https://github.com/brandcom/cakephp-vite/commit/d3e24b20aaaea63da1d509b271f96d77f9705b51

**Comment by passchn** [comment]
Release for Cake5: https://github.com/brandcom/cakephp-vite/releases/tag/v2.0.0
