### ISSUE TITLE
Allow change dev host and protocol

### ISSUE THREAD

**Issue by bor-attila** [brandcom/cakephp-vite#4]
At the moment in [ViteScriptsHelper](https://github.com/brandcom/cakephp-vite/blob/master/src/View/Helper/ViteScriptsHelper.php#L41) the development doman is fixed to **localhost** and the protocol to **http**, however not everybody uses localhost. 

Would be nice to be able to change this value

**Comment by passchn** [comment]
Could you provide a PR for that?

**Comment by bor-attila** [comment]
I already forked, fixed this issues AND I made a lot of modifications (also breaking changes).
maybe should I make a PR to develop ? ( in the worst case: reject : ) )

**Comment by passchn** [comment]
This can now be done in the latest release: https://github.com/brandcom/cakephp-vite/releases/tag/v0.3.4
