### ISSUE TITLE
.js suffix added to css entries

### ISSUE THREAD

**Issue by t0byman** [brandcom/cakephp-vite#6]
In my vite.config.js I have `styles: './resources/styles/main.css'` as an input entry. When I build, it becomes `"styles/main.css": {
    "file": "assets/main-186c74ee.css",
    "src": "styles/main.css",
    "isEntry": true
  },` in the manifest. Yet when I load my page and the manifest gets read, I get a 404 on it because it tries to get `http://localhost/assets/main-186c74ee.css.js`. **Why does it add the .js suffix?** If this is a bug, can you fix it?

I'm using PHP 8.0.24 and cakePHP 4.4.10

**Comment by passchn** [comment]
Could you provide me your full vite config, manifest.json and how and where you use the ViteScripts helper?

**Comment by t0byman** [comment]
No longer an issue in future/v1, closing
