### ISSUE TITLE
Add ability to pass js/css entry points to helper in development mode

### ISSUE THREAD

**Issue by passchn** [brandcom/cakephp-vite#9]
Code splitting is currently only possible in production mode through filters (helper), or dynamic imports within js. 

see this issue: 
https://github.com/brandcom/cakephp-vite/issues/7

**Comment by t0byman** [comment]
In my use case the paths for production manifest filters and dev script/styleEntries are exactly the same look:
```
        'development' => [
            'scriptEntries' => ['scripts/main.ts'],
            'styleEntries' => ['styles/main.css'],
            'url' => 'http://localhost:5173',
        ],
```
```
<?= $this->ViteScripts->css(['filter' => 'styles/main.css']) ?>
<?= $this->ViteScripts->script(['filter' => 'scripts/main.ts']) ?>
```
so maybe you can use the filter for both instances? Only if that works for every use case of course. Otherwise make that default and have scriptEntries and styleEntries overwrite the filter.

**Comment by passchn** [comment]
https://github.com/brandcom/cakephp-vite/releases/tag/v1-alpha7

**Comment by passchn** [comment]
@t0byman I deleted alpha7 - it was on the wrong branch. However, maybe this is now perfect for you (see example in code snippet): https://github.com/brandcom/cakephp-vite/releases/tag/v1-alpha8 

If you set the `files` option, it will override both the `devEntries` and the `filters` option. You don't have to have any option for that in your `app_vite.php` anymore. 

Does it solve your problem?

**Comment by t0byman** [comment]
Yes!
```
<?= $this->ViteScripts->css(['files' => [
        'styles/main.css',
    ]]) ?>
    <?= $this->ViteScripts->script(['files' => [
        'scripts/main.ts',
    ]]) ?>
```
works great both in dev and prod mode, you can close this I think!
